language: node_js
node_js: stable
dist: trusty
sudo: required
addons:
  firefox: latest
  sauce_connect: true
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install -g bower polymer web-component-tester
- bower install
script:
- xvfb-run wct --plugin sauce
env:
  global:
  - secure: AVBV52YCKtT1adM+sTj3FimjHQ8wp24m3erzBENpGJQ/nYWyXo+D2x3wtMDGf17K7H133V3GPYesKVDa7ARKI79Me43x5eUnlYjQUY69wr057bxg7BP03/SueldXOfHNCRXWKlChZEASHYGgIHPAPSb7REdBkD2dmtmqD5OM9IUKl416/6nCA+6oyUYvoYmCWDUpNdARUeTiLIayNrhDMPDeZIj99qybALEGaPu0pp36vXnTsh+DaWQm3unK6af63Rwk8nKgzCughwox9d5ptILoFs0tPJjz34N2eGFKqW0SBuAeQ53A9hNBJ7wnkHSTj7A5w55uqLD/NC+PHKhDxYyi0PWVzm+D++055fLle05+lHLLYAThReVMJRITVB5SbeqhEFnkS73uPJ86uwLHvHvfrLRGZhcA+ZSAhSw1j9ksnR3PqWnrDY0Sortrxvzl3SvJUHLQHynyCfThMlRgTuWYxszmV2GBdqrfPthQAHgfADmjohVduIRGU86mwoOrUNuDV7KGSg+yKOvAVNPmwoiIztYyoUG6WiTlQyd6ofvJOSDStLLVlvNoD0o+bjvpRMRO13GO+jJuyLVkowH+0zvHDlZalV+OG6pOw3FlWxzl8H0qV2K0yUHLZS5DnGGpohj+IlI0xCCT5OWap1wEQ1Ql3xzCj9TICacvvun5zvc=
  - secure: tupj1oSLo2PLFPnUVzGdkXSvDKfUQuIPqMmZUrnclRNBSsv+mPUCBjj9qu70SUNPl7EO4M/oJJElpeiuhWiM+g8jXBlGxNvfvygpyEKL5jhn+jxA3nYswu5tnN7wx2ZTj03q9FtZmRagyQozgSPM2Y4daZ0Ztpnrnwz2eXTtLLjiNJasknoYaKvUQLqhXar8wGe0P7gicsZ598IXWfqVc+sxum29hXrSpHMIqr/SSVH5/I6Nz0M8zhOvEc93zw7FBu9AXhowrkujiLw7LJNNaldaAP+g3BTFUkLJVyowI/LC/Xi9L+DXScKxwyFocQxA1y0by/1o4dw9bRIgNZ9hGY8qrHn9q8blehyM1YecqlDLuiqqqSh9ZmFqIb2ZjNmuukymPIj6RD3iQJ+EJee8iAd+VErGZUZP8Rs5EwiEJkIhAmOzgRWGTcJ9zqF1QppQ/0rqi+V3Ju3y7bM3bSsU91QCQ/DlGtGScHfgk5fqG1IzFhnJnIgTfUMYYoc8fRO96WJIpxTM0yqRcjPThAVHyZwqLkDZRBKO+3WrgGbzcKG2lP6xu0cLsu1RTaQ/ONKPgo9RPASR/TYxePv19WK+RVmyRVh8jaK0fOt/Z+rlwWS4HlWtEBRmifouWZZjvoIZYFodMqhuKyTCQnSnLCkOXHRYWbiE42HWgRMJa1WnYQQ=
