language: node_js
node_js: stable
dist: trusty
sudo: required
addons:
  firefox: latest
  sauce_connect: true
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install -g bower polymer web-component-tester
- bower install
script:
- xvfb-run wct --plugin sauce
env:
  global:
  - secure: dJ9ZtccH4zVvSvhhqIqMIUa4zUIdCKBZzv52Xp8Q7mFD7D5gWmaWzFBRJjWQONWFY+W0PYEOpiGPHWnbBL+sB7X0sHDp00e08XjwFdiM2zFyGx5dAY7yoIjkhaOr4wfAIUiRtPY5tSzjinY2AGD971n0Sk8VIwW23BLlUAxSIr8MTp3KEziOPuPrfuxq44DIfgGhwk2XoIqXOqNAq3XXXp2h6u29571NqEJ1tEHWgcjTNbIQ9s8vtQbfWB0Cuem3pdG//Tykj35ocnjFRH+5OWbp+BV7CMwqtl0fery8rY3Y3v166jtE2a1iI8AjRhmoIt3fjwfGb0MQX+CnZ3/XaxtwnphVGJPpP/GqNuZkJKxjYO7u4Tesi7Dg8U97B9RZL+b51ClGpye2PBYOOdDWyzf8AcS+8iNSfcfKiwdwB8desLjQrUawn+7IemD0hzBAEXF8iXJDx1Ql6AqcRH4EfFrO3CyBZL2g5YQZdOHfYEX9i/cSPSj/jfvJqiSznQxozXW4LmwnibNJodFv7BQ7AAqwS8lyI+a1Ht1kUKKkdweFX3DVS7JLkgnhqey56HAu2TvvZA6Dh2K2v+HJyy2CgXEWT1BB6jsEMz4+PzfV7GgyEVO4crn2SUPhKXDhHi3XtASdhIjWDx7WTb4jVUAEui9x/XfmO81Z+5MNv8iiTqw=
  - secure: Li75fiffj/eaJfJ2goYgF+0+KCu9teaaDmYxSegOtIPLFVL6anMGbGWI7JbT7euoPZjVPuEliEY4UO0nmdMI3jGcEi6bdlXBj40O1kM7dkt6bYaF0XSU/KW97z1cdyJvO+dX26CtzKLsV47kKLcw1ZN+Nch34170BVnTg7ot4G0Lp1mTQMGxp8nXKfvDBluIwFiQdce87rWOSuZO/Tsc9FVZTqkcoSHLAHkjH+z33vN/xsLiRkPd5vI+NUq+f4bRbZ5i9KzbIqfgXHgfxxbcY3fMzjceTJuVoqZcAvT1mzHp7igOg452jh8AjEKxICRSgkD8drHIMqZAHNndczONRr2y8duD0hL7VPNOxkV5nLPCiMZzTsPmQOsyHHax/z6URRGzXXTK6cj4JnHtrEH+ZGbV4qqG9G4/azld4Yb2XGYNkuBCYnsfClfkh1qAu8Wo+SZsM8CTy/TyPKvxUxxsBeGibgy+Qzr+e7B1hm5WRiWpZCGCmWW26dzabYQnbjXLg6rUzK2ugzpEO4zaj3FTru5rwDvCa+o2RwArjlV4X/0bPqSxbu7PMVRwLfTf4HatlFSXiNci9dBRnnZ4oarrJuIPlTTk3dc1QEoEgqNvf/o1VqWdInXQ5RQSGzEZCKNq/fcwSt45rVjRrzbv1QV75hLcHHU78ZJhS6B0Y38WSgM=
